set preview_images true
set preview_images_method kitty
alias travel    scout -efiklst
map f console travel%space
map / console search_inc%space
#cmap <C-j> move down=1
#cmap <C-k> move up=1
#map <C-j> move down=1
#map <C-k> move up=1

# Tab management (compatible with my neovim config)
map <tab>k tab_move 1
map <tab>j tab_move -1
map <tab>1   tab_open 1
map <tab>2   tab_open 2
map <tab>3   tab_open 3
map <tab>4   tab_open 4
map <tab>5   tab_open 5
map <tab>6   tab_open 6
map <tab>7   tab_open 7
map <tab>8   tab_open 8
map <tab>9   tab_open 9
map <tab>l   tab_shift 1
map <tab>h   tab_shift -1
map <tab>n   tab_new
map <tab>q   tab_close
map <tab>r   tab_restore

# Quiting
# unmap q
# map <C-q> quitall

# Moving to Trash instead of delete and remaping delete to dx
map dD shell -s trash-put %s
map dx console delete

