return {
    "folke/which-key.nvim",
    priority = 10000,
    opts = {
        keys = {
            scroll_down = "<C-n>",
            scroll_up = "<C-p>",
        },
        preset = "helix",
        defaults = {},
        spec = {
            {
                mode = { "n", "x" },
                { "<tab>", group = "BUFFERS" },
                { "<C-S-1><tab>", group = "TABS" },
                { "<leader>W", group = "WIKI" },
                -- { "<leader>w", group = "WINDOWS" },
                { "<leader>c", group = "CODE" },
                { "<leader>b", desc = "which_key_ignore" },
                { "<leader>u", group = "UI" },
                { "<leader>q", group = "QUIT/SESSION" },
                { "<leader>a", group = "ADMINISTRATION" },
                { "<leader>s", group = "SEARCH" },
                { "<leader>m", group = "Marks" },
                { "<leader>M", group = "MODIFY" },
                { "<leader>f", group = "FIND/FILE" },
                { "<leader>d", group = "DIFF" },
                { "<leader>x", group = "DIAGNOSTICS/QUICKFIX" },
                { "<leader>t", group = "TEST" },
                { "<leader>g", group = "GIT" },
                    { "<leader>gb", desc = "Blame line" },
                    { "<leader>gB", desc = "Browser (open)" },
                    { "<leader>gd", desc = "Diff (hunks)" },
                    { "<leader>gD", desc = "Diff (origin)" },
                    { "<leader>gf", desc = "Current File History" },
                    { "<leader>gi", desc = "GitHub Issues (open)" },
                    { "<leader>gI", desc = "GitHub Issues (all)" },
                    { "<leader>gl", desc = "Log" },
                    { "<leader>gL", desc = "Log (cwd)" },
                    { "<leader>gs", desc = "Status" },
                    { "<leader>gS", desc = "Stash" },
                    { "<leader>gY", desc = "Browser (copy link)" },
                    { "<leader>gG", group ="NEOGIT" },
                { "<leader>h", group = "HUNK" }, -- Should be merged with GIT
                { "<C-S-1>S",                                                                 group = "SORT" },
                { "<C-S-1>Q",                                                                 group = "QUIT" },
                -- KEYMAPS HELP
                { "<leader>?",                                                                group = "KEYMAPS MENU", },
                    { "<leader>?" .. vim.g.debugLeader,
                        function() require("which-key").show(vim.g.debugLeader) end,              group = "DEBUG", },
                    { "<leader>??", function() require("which-key").show({ global = false }) end, group = "NO-PREFIX BUFFER LOCAL KEYMAPS", },
                    { "<leader>?" .. vim.g.tabLeader, function() require("which-key").show("<C-S-1>") end,      group = "BUFFERS/TABS", },
                    { "<leader>?<leader>", function() require("which-key").show("<leader>") end,  group = "LEADER", },
                    -- KEYMAP HELP: General commands
                    { "<leader>?<cr>", group = "NO-PREFIX COMMANDS" },
                        { "<leader>?<cr>" .. "<C-s>", desc = "Save buffer" },
                        { "<leader>?<cr>" .. "<C-S-s>", desc = "Save all buffers" },
                        { "<leader>?<cr>" .. "<C-/>", desc = "Terminal (root dir)" },
                        { "<leader>?<cr>" .. "<C-S-/>", desc = "Terminal (cwd)" },

                    -- SEEKER MENU
                    { vim.g.seekerLeader, function() require("which-key").show({ keys = "<leader>s" }) end,  group = "SEARCH/FIND", },
                    { "<leader>s;", function() require("which-key").show("<leader>f") end,                   group = "FIND", },
                    { "<leader>s<Tab>", function() Snacks.picker.buffers() end,                              desc = "Find buffer (shortcut)" },
            },
        },
    },
}
