#!/bin/bash

VPN_CONF="$HOME/.wg/WGHome.conf"
# VPN_ADDRESS="vpn.my-host.org"
# VPN_PORT="20743"

function usage() {
    echo -e "Description:"
    echo -e "\tStarts/stops connection to my private VPN.\n"
    echo -e "Usage:"
    echo -e "\ts_vpn action\n"
    echo -e ""
    echo -e "\taction     - Available actions: on, off.\n"
    echo -e "Options:"
    echo -e "\t-h         - Print help."
}

arg1=$1

if [ $# -lt 1 ] || [ "$arg1" == "-h" ]; then
    usage
    exit
fi

if [[ "$arg1" != "on" ]] && [[ "$arg1" != "off" ]]; then
    echo x
    usage
    exit
fi

if [ "$arg1" == "on" ]; then
    sudo wg-quick up $VPN_CONF
    # VPN_IP=$(getent ahosts $VPN_ADDRESS| awk '{print $1; exit}')
    # sudo ip link add wg0 type wireguard
    # sudo ip addr add 10.104.207.4/24 dev wg0
    # sudo wg set wg0 listen-port $VPN_PORT private-key ~/.wg/WG-SC.key
    # sudo wg set wg0 peer Xg8atxj7sG2BjCZMnqDnS5KK1Q6JK/SQ1jKYCYRq6j0= preshared-key ~/.wg/WG-SC-pre.psk endpoint $VPN_IP:$VPN_PORT allowed-ips 10.104.207.1/32,192.168.0.0/24
    # sudo ip link set wg0 up
    # sudo ip route add 192.168.0.0/24 dev wg0
    # sudo systemctl restart systemd-resolved
    # exit
fi

if [ "$arg1" == "off" ]; then
    sudo wg-quick down $VPN_CONF
    # sudo ip link del wg0 type wireguard
    exit
fi

