# vi: foldmethod=marker foldmarker=#{,#} nowrap

# Keybindings
    map Ctrl+Shift+e show_scrollback
    map Ctrl+shift+q no_op
    map Ctrl+Shift+minus change_font_size all -1
    map Ctrl+Shift+equal change_font_size all +1
    map Ctrl+Shift+s noop

# Settings
    enable_audio_bell no
    shell_integration no-cursor
    confirm_os_window_close -1
    window_padding_width 4
    # for nvim regexplainer:
    #allow_remote_control true 

    startup_session ~/.config/kitty/sessions/kitty-startup.session

# Scrollback command
    scrollback_pager nvim -c ':write! ~/.local/share/nvim/scrollback.tmp' -c 'set nonumber' -c 'nmap q :q!<CR>' -c 'map <C-s> G?\$<CR>ll:noh<CR>l' -c 'terminal tail -F -n 100000 ~/.local/share/nvim/scrollback.tmp' -c 'set modifiable'
    #{ Old scrollback commands
        #scrollback_pager nvim -c 'setlocal ft=man number modifiable noro relativenumber nolist showtabline=0 foldcolumn=0' -c "autocmd VimEnter * normal G" -c ":silent! %s#\($\n\s*\)\+\%$##" - 
        #scrollback_pager nvim -c 'setlocal ft=man nonumber nolist showtabline=0 foldcolumn=0' -c "autocmd VimEnter * normal G" -
    #}

# BEGIN_KITTY_THEME
# OneDark-Pro
include current-theme.conf
# END_KITTY_THEME

# Colors
    background #151515
    background_opacity 0.95

# Font
    font_size    11
    #symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono
# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
